---
# General
# Make sure you update these before running the playbook
abuseio_hostname: "demo2.abuse.io"
ssh_admin_cidr: "0.0.0.0/0"

# AbuseIO 
abuseio_db_name: "abuseio"
abuseio_db_user: "abuseio"
abuseio_db_password: "CHANGE_ME_DB_USER_PASSWORD"
abuseio_git_version: "5.0" 

# MariaDB
mysql_root_password: "CHANGE_ME_SECURE"

# AbuseIO admin
abuseio_admin_username: "admin@isp.local"
abuseio_admin_contact:  "admin@isp.local"
abuseio_admin_password: "ispadmin"

## Lynis subsets toggles (enabled by default)
hardening_lynis_low_enabled: true
hardening_lynis_medium_enabled: true
hardening_lynis_suggestions_enabled: true
